language: go

sudo: false

addons:
 apt:
   packages:
    - libmpv-dev

go:
 - "1.11"
 - "tip"

env:
 - GO111MODULE=on

script:
 - go build github.com/ghedo/grooved/cmd/grooved
 - go build github.com/ghedo/grooved/cmd/groovectl
