.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GROOVED" "1" "May 2014" "" ""
.
.SH "NAME"
\fBgrooved\fR \- groovy music player daemon
.
.SH "SYNOPSIS"
\fBgrooved [OPTIONS]\fR
.
.SH "DESCRIPTION"
\fBgrooved\fR is a stupidly simple music player that runs as a daemon instead of showing a fancy GUI\. I\'m kinda lazy, so instead or re\-implementing some of the features that make up a music player, I just used stuff someone else already built\. For example, grooved uses mpv to reproduce audio instead of implementing its own half\-working audio decoder and player, and piggybacks on tools like beets instead of implementing yet another music database\. Life gets so much better once you let other people do the hard work\.
.
.SH "OPTIONS"
\fB\-c, \-\-config=<file>\fR
.
.P
\~\~\~\~\~\~ Specify the configuration file\. (default: \fB~/\.config/grooved/config\.ini\fR)
.
.P
\fB\-V, \-\-verbose\fR
.
.P
\~\~\~\~\~\~ Enable verbose log messages\.
.
.SH "CONFIG"
Here is a list of valid configuration options:
.
.P
\fBlibrary=<path>\fR
.
.P
\~\~\~\~\~\~ The path to beets\' database\.
.
.P
\fBverbose=on|off\fR
.
.P
\~\~\~\~\~\~ Whether to enable verbose output\. (optional)
.
.P
\fBgapless=on|off\fR
.
.P
\~\~\~\~\~\~
.
.P
Whether to play consecutive audio files with no silence or disruption at the point of file change\. (optional)
.
.P
\fBfilter=<filter>\fR
.
.P
\~\~\~\~\~\~ Filter audio with the given filter\. Can be specified multiple times, in which case filters get chained one after the other\. See mpv(1) for a list of supported filters and options\. (optional)
.
.P
\fBoutput=<output>\fR
.
.P
\~\~\~\~\~\~ The output audio driver to use\. See mpv(1) for a list of suported audio outputs and options\. (optional)
.
.SH "AUTHOR"
Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.SH "COPYRIGHT"
Copyright (C) 2014 Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.P
This program is released under the 2 clause BSD license\.
