.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GROOVECTL" "1" "November 2014" "" ""
.
.SH "NAME"
\fBgroovectl\fR \- groovy music player client
.
.SH "SYNOPSIS"
\fBgroovectl COMMAND [ARGS]\fR
.
.SH "DESCRIPTION"
\fBgroovectl\fR is a command\-line client for grooved\. It communicates with the grooved daemon via the DBus session bus\.
.
.SH "COMMANDS"
\fBplay\fR
.
.P
\~\~\~\~\~\~ Unpause the player\.
.
.P
\fBpause\fR
.
.P
\~\~\~\~\~\~ Pause the player\.
.
.P
\fBtoggle\fR
.
.P
\~\~\~\~\~\~ Toggle the player\'s pause status\.
.
.P
\fBnext\fR
.
.P
\~\~\~\~\~\~ Skip to the next track\.
.
.P
\fBprev\fR
.
.P
\~\~\~\~\~\~ Skip to the previous track\.
.
.P
\fBstop\fR
.
.P
\~\~\~\~\~\~ Stop playback and clear tracklist\.
.
.P
\fBadd TRACK\fR
.
.P
\~\~\~\~\~\~ Append tracks to the player\'s tracklist\. Tracks can be either files on the filesystem or other kinds of streams (e\.g\. HTTP streams, Youtube videos, \.\.\.)\.
.
.P
\fBload [\-\-append] FILE\fR
.
.P
\~\~\~\~\~\~ Load a playlist file\. The tracklist will be replaced with the content of the given playlist and playback stopped, unless \fB\-\-append\fR is used\.
.
.P
\fBsave FILE\fR
.
.P
\~\~\~\~\~\~ Save the tracklist to a playlist file\.
.
.P
\fBgoto INDEX\fR
.
.P
\~\~\~\~\~\~ Skip to a specific track, identified by its index, in the tracklist\.
.
.P
\fBrm INDEX\fR
.
.P
\~\~\~\~\~\~ Remove a track identified by its index in the tracklist, from the tracklist\. The special value \fB\-1\fR corresponds to the current track\.
.
.P
\fBls\fR
.
.P
\~\~\~\~\~\~ Show tracklist (the current track is marked with \'*\')\.
.
.P
\fBstatus\fR
.
.P
\~\~\~\~\~\~ Show the status of the player\.
.
.P
\fBseek SECONDS\fR
.
.P
\~\~\~\~\~\~ Seek by the given amount of seconds relative to the current position\. A negative value seeks backwards\.
.
.P
\fBloop track|list|none\fR
.
.P
\~\~\~\~\~\~ Set the player\'s loop mode\.
.
.P
\fBquit\fR
.
.P
\~\~\~\~\~\~ Shutdown the player\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.SH "COPYRIGHT"
Copyright (C) 2014 Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.P
This program is released under the 2 clause BSD license\.
